#! /bin/bash

# Launch sxhkd hotkey daemon if it hasn't been done yet. Because bspwm is a
# lazy one and doen't mess with stuff like that.

pgrep -x sxhkd > /dev/null || sxhkd &

# Set up workspaces. I like them to be numbered from one to eight, but you can
# come up with something completely different.

bspc monitor -d 1 2 3 4 5 6 7 8

# Set the window gap. I like to have twelve pixels between them, but it's also
# a matter of taste.

bspc config window_gap 12

# Set the window border width. Two pixels are quite enough for me to notice the
# difference of border color.

bspc config border_width 2

# Set the normal and focused border colors. Those values are chosen to match
# the Tokyo Night color theme.

bspc config  normal_border_color "#1d202f"
bspc config focused_border_color "#414868"

# Set the window split ratio. I like windows to be evenly split, but you can
# try the golden ratio too. By the way, it is roughly 0.62...

bspc config split_ratio 0.5

# Set the window focus to follow mouse and vice versa. Sometimes it looks like
# a funny cat trying to catch a laser pointer...

bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# Make bspwm tile zathura windows. Because it doesn't work like that by
# default.

bspc rule -a Zathura state=tiled

# Set the window manager name to LG3D. Otherwise Java-powered applications are
# very suspicious about it.

wmname LG3D

# Launch pcmanfm desktop daemon in the background. It also manages the
# wallpaper.

pcmanfm --desktop &

# Launch polybar status bar in the background. I have a special script to do
# the trick.

~/.config/polybar/launch.sh &

# Launch picom compositor in the background. Everyone loves transparent
# terminals and nice transitions!

picom -CGb &

# Launch dunst desktop notification daemon in the background. It has its own
# configuration file, by the way.

dunst &

# Launch my battery status notification script in the background. It sends
# notification when the battery is low.

~/.config/bspwm/scripts/battery.sh &
